# suppress inspection "UnusedProperty" for whole file
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5433/coin_game'
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false

  security:
    user:
      name: postgres
      user:
        password: admin

security:
  oauth2:
    resource:
      filter-order: 3

  signing-key: MaYzkSjmkzPC57L
  encoding-strength: 10
  security-realm: CoinGame REALM

  jwt:
    client-id: CoinGame
    client-secret: CoinGame
    grant-type: password
    scope-read: read
    scope-write: write
    resource-ids: testjwtresourceid
    refresh: refresh_token
